require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/provinces", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Province. As you add validations to Province, be sure to
  # adjust the attributes here as well.
  before(:each) do
    @current_user = FactoryBot.create(:user)
    @new_auth_header = @current_user.create_new_auth_token
  end

  let(:valid_attributes) {
    { "name" => "Province Name" }
  }

  let(:invalid_attributes) {
    { "name" => "" }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ProvincesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Province.create! valid_attributes
      get provinces_url, headers: @new_auth_header
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      province = Province.create! valid_attributes
      get province_url(province), headers: @new_auth_header
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Province" do
        expect {
          post provinces_url,
               params: { province: valid_attributes }, headers: @new_auth_header
        }.to change(Province, :count).by(1)
      end

      it "renders a JSON response with the new province" do
        post provinces_url,
             params: { province: valid_attributes }, headers: @new_auth_header
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Province" do
        expect {
          post provinces_url,
               params: { province: invalid_attributes }, as: :json
        }.to change(Province, :count).by(0)
      end

      it "renders a JSON response with errors for the new province" do
        post provinces_url,
             params: { province: invalid_attributes }, headers: @new_auth_header
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { "name" => "New Province Name" }
      }

      it "updates the requested province" do
        province = Province.create! valid_attributes
        patch province_url(province),
              params: { province: new_attributes }, headers: @new_auth_header
        province.reload
        expect(assigns(:province).attributes['name']).to eq(new_attributes['name'])
      end

      it "renders a JSON response with the province" do
        province = Province.create! valid_attributes
        patch province_url(province),
              params: { province: new_attributes }, headers: @new_auth_header
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the province" do
        province = Province.create! valid_attributes
        patch province_url(province),
              params: { province: invalid_attributes }, headers: @new_auth_header
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested province" do
      province = Province.create! valid_attributes
      expect {
        delete province_url(province), headers: @new_auth_header
      }.to change(Province, :count).by(-1)
    end
  end
end
